### ISSUE TITLE
Specify YQ version to install

### ISSUE THREAD

**Issue by pedro93** [chrisdickinson/setup-yq#10]
Hello,

Is there a way to specify the YQ version that a user wants installed in their action?

Thank you for making this project!

**Comment by pedro93** [comment]
Found the solution, for reference:
```
      - name: Download YQ
        uses: chrisdickinson/setup-yq@v1.0.0
        with:
          yq-version: 4.28.2
```
