### ISSUE TITLE
`yq` installed version (v3) unmaintained

### ISSUE THREAD

**Issue by Saviq** [chrisdickinson/setup-yq#5]
The v3 version of YQ is unmaintained, yet that's what this action installs.

https://mikefarah.gitbook.io/yq/v/v3.x/

**Comment by tombailey** [comment]
You can try

```yaml
- uses: chrisdickinson/setup-yq@v1.0.1
  with:
    yq-version: v4.25.3
```

or another version listed in the releases [here](https://github.com/mikefarah/yq/releases/tag/v4.25.3)
