### ISSUE TITLE
Run set-yq failed. The add-path command is disabled.

### ISSUE THREAD

**Issue by lazychanger** [chrisdickinson/setup-yq#7]
[build](https://github.com/lazychanger/helm-viv/actions/runs/3239246933/jobs/5308399561#step:4:9)
The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by lazychanger** [comment]
```yaml
    steps:
      - name: setup-yq
        uses: chrisdickinson/setup-yq@v1.0.0
        with:
          yq-version: v4.25.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true
```
